name: Build

on:
  push:
    branches:
      - master
      - test-* # make it be easier for contributors to test
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'master'

jobs:
  BuildJava8Runtime:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Docker meta for KubeSphere
      id: meta
      if: github.repository_owner == 'kubesphere'
      uses: docker/metadata-action@v3
      with:
        images: |
          kubespheredev/java-8-runtime
          ghcr.io/${{ github.repository_owner }}/java-8-runtime
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Docker meta for Contributors
      id: metaContributors
      if: github.repository_owner != 'kubesphere'
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/java-8-runtime
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_SECRETS }}
    - name: Login to GHCR
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.4.0
      if: github.repository_owner == 'kubesphere'
      with:
        context: java8
        tags: ${{ steps.meta.outputs.tags }}
        push: ${{ github.event_name != 'pull_request' }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
    - name: Build and push Docker images for Contributors
      uses: docker/build-push-action@v2.4.0
      if: github.repository_owner != 'kubesphere'
      with:
        context: java8
        tags: ${{ steps.metaContributors.outputs.tags }}
        push: ${{ github.event_name != 'pull_request' }}
        labels: ${{ steps.metaContributors.outputs.labels }}
        platforms: linux/amd64,linux/arm64

  BuildJava11CentOS7:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Docker meta for KubeSphere
      id: meta
      if: github.repository_owner == 'kubesphere'
      uses: docker/metadata-action@v3
      with:
        images: |
          kubespheredev/java-11-centos7
          ghcr.io/${{ github.repository_owner }}/java-11-centos7
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Docker meta for Contributors
      id: metaContributors
      if: github.repository_owner != 'kubesphere'
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/java-11-centos7
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_SECRETS }}
    - name: Login to GHCR
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.4.0
      if: github.repository_owner == 'kubesphere'
      with:
        context: java11
        tags: ${{ steps.meta.outputs.tags }}
        push: ${{ github.event_name != 'pull_request' }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
    - name: Build and push Docker images for Contributors
      uses: docker/build-push-action@v2.4.0
      if: github.repository_owner != 'kubesphere'
      with:
        context: java11
        tags: ${{ steps.metaContributors.outputs.tags }}
        push: ${{ github.event_name != 'pull_request' }}
        labels: ${{ steps.metaContributors.outputs.labels }}
        platforms: linux/amd64,linux/arm64

  BuildTomcat85Java8Runtime:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Docker meta for KubeSphere
      id: meta
      if: github.repository_owner == 'kubesphere'
      uses: docker/metadata-action@v3
      with:
        images: |
          kubespheredev/tomcat85-java8-runtime
          ghcr.io/${{ github.repository_owner }}/tomcat85-java8-runtime
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Docker meta for Contributors
      id: metaContributors
      if: github.repository_owner != 'kubesphere'
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/tomcat85-java8-runtime
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_SECRETS }}
    - name: Login to GHCR
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.4.0
      if: github.repository_owner == 'kubesphere'
      with:
        context: tomcat85-java8
        tags: ${{ steps.meta.outputs.tags }}
        push: ${{ github.event_name != 'pull_request' }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
    - name: Build and push Docker images for Contributors
      uses: docker/build-push-action@v2.4.0
      if: github.repository_owner != 'kubesphere'
      with:
        context: tomcat85-java8
        tags: ${{ steps.metaContributors.outputs.tags }}
        push: ${{ github.event_name != 'pull_request' }}
        labels: ${{ steps.metaContributors.outputs.labels }}
        platforms: linux/amd64,linux/arm64

  BuildTomcat85Java11Runtime:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Docker meta for KubeSphere
      id: meta
      if: github.repository_owner == 'kubesphere'
      uses: docker/metadata-action@v3
      with:
        images: |
          kubespheredev/tomcat85-java11-runtime
          ghcr.io/${{ github.repository_owner }}/tomcat85-java11-runtime
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Docker meta for Contributors
      id: metaContributors
      if: github.repository_owner != 'kubesphere'
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/tomcat85-java11-runtime
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_SECRETS }}
    - name: Login to GHCR
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.4.0
      if: github.repository_owner == 'kubesphere'
      with:
        context: tomcat85-java11
        tags: ${{ steps.meta.outputs.tags }}
        push: ${{ github.event_name != 'pull_request' }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
    - name: Build and push Docker images for Contributors
      uses: docker/build-push-action@v2.4.0
      if: github.repository_owner != 'kubesphere'
      with:
        context: tomcat85-java11
        tags: ${{ steps.metaContributors.outputs.tags }}
        push: ${{ github.event_name != 'pull_request' }}
        labels: ${{ steps.metaContributors.outputs.labels }}
        platforms: linux/amd64,linux/arm64
